import "./globals.css";

export default function Layout({ children }: Readonly<{ children: React.ReactNode; }>)
{
	return (
		<html>
			<body>
			{
				children
			}
			</body>
	  	</html>
	);
}

/** @type {import("next").Metadata} */
export const metadata = { title: "Create Next App", description: "Generated by create next app" };
